name: trigger-circleci
on:
  push:
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger circleci
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.4
        env:
          CCI_TOKEN: $
